name: ci 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  style:
    runs-on: ubuntu-latest
    name: check-style 
    steps:
    - uses: actions/checkout@v4

    - name: configure 
      run: cmake -S . -B build
  
    # FIXME
    # - name: format-check
    #   run: cmake --build build --target format-check

    # - name: lint
    #   run: cmake --build build --target lint

  build:
    runs-on: ubuntu-latest
    name: build with cmake
    steps:
    - uses: actions/checkout@v4
    
    - name: configure 
      run: cmake -DCMAKE_BUILD_TYPE=Release -S . -B build

    - name: build 
      run: cd build; make
